// Generates the blog into <repo>/blog/, plus sitemap.xml and robots.txt.
//
// Mirrors resume/build-pdf.mjs: a plain Node script that CI runs before the
// Pages artifact is uploaded, so the deployed site always matches the Markdown
// in content/blog/. Nothing it writes is committed.
//
//   node tools/blog/build.mjs            # published posts only
//   BLOG_DRAFTS=1 node tools/blog/build.mjs   # include drafts, for local preview

import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PATHS, SITE } from "./config.mjs";
import { loadPosts } from "./content.mjs";
import { renderMarkdown } from "./markdown.mjs";
import { renderJsonFeed, renderRobots, renderRss, renderSitemap } from "./feeds.mjs";
import { readingTime, stripHtml, truncate } from "./text.mjs";
import { renderIndex, renderPost, renderTagIndex, renderTagPage } from "./templates.mjs";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

// Dropped into the output directory so the next build can prove the directory
// is ours before deleting it.
const MARKER = ".generated";
const MARKER_TEXT =
  "Generated by tools/blog/build.mjs. Everything in this directory is\n" +
  "rewritten on every build — edit content/blog/*.md instead.\n";

/** Strip code blocks before measuring prose: code is not read at 200 wpm. */
const proseOf = (html) => stripHtml(html.replace(/<pre[\s\S]*?<\/pre>/g, " "));

/** First paragraph, trimmed — used when a post omits `description`. */
function deriveDescription(html) {
  const paragraph = /<p(?:\s[^>]*)?>([\s\S]*?)<\/p>/.exec(html);
  return paragraph ? truncate(stripHtml(paragraph[1]), 180) : "";
}

function collectTags(posts) {
  const bySlug = new Map();
  for (const post of posts) {
    for (const tag of post.tags) {
      const entry = bySlug.get(tag.slug);
      if (entry) {
        entry.posts.push(post);
        if (entry.name !== tag.name) entry.aliases.add(tag.name);
      } else {
        bySlug.set(tag.slug, { ...tag, posts: [post], aliases: new Set() });
      }
    }
  }
  return [...bySlug.values()]
    .map((tag) => ({ ...tag, count: tag.posts.length }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, "en"));
}

/** Posts sharing the most tags with `post`; never padded with unrelated filler. */
function findRelated(post, posts, limit = 3) {
  const own = new Set(post.tags.map((tag) => tag.slug));
  if (!own.size) return [];
  return posts
    .filter((other) => other.slug !== post.slug)
    .map((other) => ({
      post: other,
      shared: other.tags.filter((tag) => own.has(tag.slug)).length,
    }))
    .filter((entry) => entry.shared > 0)
    .sort((a, b) => b.shared - a.shared || b.post.date - a.post.date)
    .slice(0, limit)
    .map((entry) => entry.post);
}

async function write(path, contents) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, "utf8");
}

/**
 * Remove the previous output so renamed or deleted posts do not linger as
 * orphaned pages — but only after confirming the directory is one we generated.
 */
async function resetOutput(outDir) {
  let entries;
  try {
    entries = await readdir(outDir);
  } catch (error) {
    if (error.code === "ENOENT") return;
    throw error;
  }
  if (entries.length && !entries.includes(MARKER)) {
    throw new Error(
      `Refusing to overwrite ${outDir}: it is not empty and has no ${MARKER} marker,\n` +
        "so it was not created by this script. Move it aside if that is unexpected.",
    );
  }
  await rm(outDir, { recursive: true, force: true });
}

/**
 * Every path is injectable so the integration test can build a fixture corpus
 * into a temporary directory instead of over the real site.
 */
export async function build({
  contentDir = resolve(repoRoot, PATHS.content),
  outDir = resolve(repoRoot, PATHS.outDir),
  rootDir = repoRoot,
  includeDrafts = process.env.BLOG_DRAFTS === "1",
  year = new Date().getUTCFullYear(),
  log = console,
} = {}) {
  const posts = await loadPosts({ dir: contentDir, includeDrafts });

  for (const post of posts) {
    const { html, headings } = renderMarkdown(post.body, { baseDir: post.dir });
    const prose = proseOf(html);
    post.html = html;
    post.headings = headings;
    post.wordCount = prose.split(/\s+/).filter(Boolean).length;
    post.readingMinutes = readingTime(prose);
    if (!post.description) post.description = deriveDescription(html) || post.title;
  }

  const tags = collectTags(posts);

  for (const tag of tags) {
    if (tag.aliases.size) {
      log.warn(
        `! tag "${tag.name}" shares the URL /blog/tags/${tag.slug}/ with ` +
          `${[...tag.aliases].map((name) => `"${name}"`).join(", ")} — they are merged.`,
      );
    }
  }

  await resetOutput(outDir);
  await write(join(outDir, MARKER), MARKER_TEXT);

  await write(join(outDir, "index.html"), renderIndex({ posts, tags, year }));

  for (const [index, post] of posts.entries()) {
    await write(
      join(outDir, post.slug, "index.html"),
      renderPost({
        post,
        newer: posts[index - 1] ?? null,
        older: posts[index + 1] ?? null,
        related: findRelated(post, posts),
        year,
      }),
    );
  }

  if (tags.length) {
    await write(join(outDir, "tags", "index.html"), renderTagIndex({ tags, year }));
    for (const tag of tags) {
      await write(
        join(outDir, "tags", tag.slug, "index.html"),
        renderTagPage({ tag, posts: tag.posts, year }),
      );
    }
  }

  await write(join(outDir, "rss.xml"), renderRss(posts));
  await write(join(outDir, "feed.json"), renderJsonFeed(posts));
  await write(resolve(rootDir, "sitemap.xml"), renderSitemap({ posts, tags }));
  await write(resolve(rootDir, "robots.txt"), renderRobots());

  const drafts = includeDrafts ? " (drafts included)" : "";
  log.log(
    `✓ Blog built${drafts}: ${posts.length} post${posts.length === 1 ? "" : "s"}, ` +
      `${tags.length} tag${tags.length === 1 ? "" : "s"} → ${outDir}`,
  );
  if (!posts.length) {
    log.log(`  (no published posts found in ${contentDir})`);
  }

  return { posts, tags };
}

// Only build when run as a script — the tests import the helpers above.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  build().catch((error) => {
    console.error(`\n✗ Blog build failed.\n\n${error.message}\n`);
    process.exitCode = 1;
  });
}

export { collectTags, deriveDescription, findRelated, proseOf };
